### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by normal-painter** [MohamedBassem/hoarder-app#60]
Hello! Thank you for the amazing work. This seems like an amazing application. I am trying to get this running on unraid with docker compose, but when I try to do so with the following docker compose

`version: "3.8"
services:
  web:
    image: ghcr.io/mohamedbassem/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 3000:3000
    env_file:
      - settings.env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - settings.env
    volumes:
      - meilisearch:/meili_data
  workers:
    image: ghcr.io/mohamedbassem/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    env_file:
      - settings.env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      # OPENAI_API_KEY: ...
    depends_on:
      web:
        condition: service_started

volumes:
  redis:
  meilisearch:
  data:`

and the following env

`DATA_DIR=/mnt/user/appdata/hoarder/data
NEXTAUTH_SECRET=ee2r…F
HOARDER_VERSION=release
MEILI_MASTER_KEY=20…RPn3s8t1`

I get the an error stating something went wrong. 

I’m not sure if it’s related, but in the logs I’m seeing the following error:
sqliteerror: FOREIGN KEY constraint failed

Any thoughts on what I am doing wrong?

Thank you in advance!

**Comment by MohamedBassem** [comment]
Hey, I think I see the problem. `DATA_DIR` should point to the path inside the container and in this case, should remain `/data` as is.

What you want to do is to replace the volumes in the docker compose with the host path. For example:

```
  web:
    image: ghcr.io/mohamedbassem/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/hoarder/data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
```

Notice how the volumes section now points to your host path.

You'll need to change this for all the containers that have `volumes`.
So web: `/mnt/user/appdata/hoarder/data`
redis: `/mnt/user/appdata/hoarder/redis`
meilisearch `/mnt/user/appdata/hoarder/meili`
workers `/mnt/user/appdata/hoarder/data`

Notice that web and workers should share the same path.
