### ISSUE TITLE
Make installation available on Unraid OS

### ISSUE THREAD

**Issue by Augusto271** [MohamedBassem/hoarder-app#81]
Hello,

Having a docker app ready for unraid that shows in their docker store would make it easier for unraid users to install it faster.

Cheers!

**Comment by MohamedBassem** [comment]
I understand how convenient it is for hoarder to be available in the unraid store. Unfortunately, as far as I know, unraid store doesn't support having multi-container deployments. They'll need to be separate services as far as I know which won't be that easy to setup.

It might be easier to use the "Docker compose manager" plugin (https://forums.unraid.net/topic/114415-plugin-docker-compose-manager/) to set up hoarder instead.

**Comment by bob912** [comment]
It really isn't hard to get Hoarder running under Unraid. Install Docker Compose Manager, copy in compose file, set a couple of variables in .env per the install docs. Took me less than 5 min to have it running.

Dockerman in Unraid is very limiting - it's worth the effort to learn how to do Docker things, and especially Compose things, outside of it.

**Comment by Javican** [comment]
I would jump on board if i see a unraid rocker image!!

**Comment by TheSylus** [comment]
@bob912 
Could you please post your docker-compose.yml?
Basicly I got it running, but for me it is not clear which part of the yml file I have to change to make the folder/files persistent. Where are the files stored right now?
Do I only have to change  DATA_DIR: /data??
THX

**Comment by MohamedBassem** [comment]
@TheSylus typically you shouldn't change the DATA_DIR var. This should stay '/data'.

If you want to make your data persistent, you change what /data gets mapped to.

So this line that says:
- data:/data

should be
- /path/on/disk:/data

change that for all the containers

**Comment by bob912** [comment]
@TheSylus Change the volume definitions of each container to include a real path as mentioned by @MohamedBassem and comment out the internal volume definitions at the bottom. 
```yaml
version: "3.8"
services:
  web:
    image: ghcr.io/mohamedbassem/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
#      - data:/data
      - /mnt/user/appdata/hoarder/data:/data:rw
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
#      - redis:/data
      - /mnt/user/appdata/hoarder/data:/data:rw

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:100
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    volumes:
#      - meilisearch:/meili_data
      - /mnt/user/appdata/hoarder/meili_data:/meili_data:rw
  workers:
    image: ghcr.io/mohamedbassem/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
#      - data:/data
      - /mnt/user/appdata/hoarder/data:/data:rw
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      # OPENAI_API_KEY: ...
    depends_on:
      web:
        condition: service_started

#volumes:
#  redis:
#  meilisearch:
#  data:
```
