### ISSUE TITLE
No images are fetched

### ISSUE THREAD

**Issue by DominikBritz** [MohamedBassem/hoarder-app#83]
I don't see images in hoarder when adding links.

Example link added: https://mariushosting.com/how-to-install-hoarder-on-your-synology-nas

![image](https://github.com/MohamedBassem/hoarder-app/assets/11243580/e4575546-8464-4195-ad49-146a86b74f5a)

Below is my compose file.

```
version: "3.8"
services:
  web:
    image: ghcr.io/mohamedbassem/hoarder-web:${HOARDER_VERSION:-release}
    restart: unless-stopped
    hostname: hoarder
    container_name: hoarder-web
    user: 2000:2000
    volumes:
      - ./data:/data
    expose:
      - 3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
    networks:
      - caddy_caddynet
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    container_name: hoarder-redis
    volumes:
      - redis:/data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    container_name: hoarder-chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    container_name: hoarder-meili
    env_file:
      - .env
    volumes:
      - meilisearch:/meili_data
  workers:
    image: ghcr.io/mohamedbassem/hoarder-workers:${HOARDER_VERSION:-release}
    restart: unless-stopped
    container_name: hoarder-workers
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      # OPENAI_API_KEY: ...
    depends_on:
      web:
        condition: service_started
volumes:
  redis: null
  meilisearch: null
networks:
  caddy_caddynet:
    external: true
```
